# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Mod properties
mod_id=modernfix
version=5.26.3-build.1

# Minecraft/Fabric
minecraft_version=1.21.11
loader_version=0.18.4
loom_version=1.14-SNAPSHOT

# Fabric API
fabric_api_version=0.140.2+1.21.11

# Dependencies
mixinextras_version=0.4.1
modmenu_version=17.0.0-alpha.1

# For mod sites
supported_minecraft_versions=1.21.11

# Build
shadow_version=8.1.1
