# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# org.gradle.java.home=C:/jdk-25.0.2

# Mod properties
mod_id=modernfix
version=5.27.7-build.1

# Minecraft/Fabric
minecraft_version=26.2-snapshot-5
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Fabric API
fabric_api_version=0.147.1+26.2

# Dependencies
mixinextras_version=0.4.1
modmenu_version=18.0.0-alpha.8

# For mod sites
supported_minecraft_versions=~26.2-

# Build
shadow_version=8.1.1
